# Generated by Django 6.0.6 on 2026-06-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_notice_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty/'),
        ),
    ]
