# Generated by Django 5.2.4 on 2026-06-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
